name: sunday-cron
on:
  schedule:
    - cron: '*/2 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          curl --request POST \
          --url 'localhost:3000/api/bot' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}' \
          --console.log(message)