name: sunday-cron
on:
  schedule:
    - cron: '5 17 * * 2'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
      - env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          curl --request POST \
          --url 'telegram-bot-seven-woad.vercel.app' \
          --header `Authorization: Bearer ${process.env.TOKEN}`