name: sunday-cron
on:
  schedule:
    - cron: '35 16 * * 0'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Telegram API route
        run: |
          curl --request GET \
          --url 'https://telegram-bot-bookcliff.vercel.app/api/bot'